+ added a includetest rules to src/Makefile.am to check if all headers compile   correctly if included on their own * adds a few includes/dclarations to make includetest happy * gloox::Tag::TagList -> gloox::TagList
git-svn-id: svn://svn.camaya.net/gloox/trunk@2909 bb60cc1b-8fe5-0310-9879-aca5d778a633

diff --git a/src/Makefile.am b/src/Makefile.am
--- a/src/Makefile.am
+++ b/src/Makefile.am
@@ -91,3 +91,12 @@ leaktest:
 	make -C tests leaktest
 
 leakcheck: leaktest
+
+includetest:
+	@for i in *.h; do \
+	  echo -e "#include \"$$i\"\nint main() {}" >tmp.cpp; \
+	  $(CXX) -I.. tmp.cpp 2>&1 | sed "s/^$$i://g" >$$i.test.log; \
+	  test -s $$i.test.log && echo "INC $$i: failed" || rm $$i.test.log; \
+	done
+	@rm tmp.cpp
+	@ls *.h.test.log &>/dev/null || echo "INC all: ok"
